Main makefile tweak: improved checks for JAVA_DIR etc.
git-svn-id: https://www.prismmodelchecker.org/svn/prism/prism/trunk@18 bbc10eb1-c90d-0410-af57-cb519fbb1720

diff --git a/prism/Makefile b/prism/Makefile
--- a/prism/Makefile
+++ b/prism/Makefile
@@ -411,13 +411,17 @@ checks:
 	  echo "after the -> arrow. You can then deduce what the directory is as above."; \
 	  exit 1; \
 	fi; \
+	if [ ! -d $(JAVA_DIR) ]; then \
+	  echo "Java directory $(JAVA_DIR) does not exist."; \
+	  exit 1; \
+	fi; \
 	if [ ! -f $(JAVA_JNI_H_DIR)/jni.h ]; then \
-	  echo "Failed to locate the JNI header $(JAVA_JNI_H_DIR)/jni.h."; \
+	  echo "Failed to locate the JNI header jni.h."; \
 	  echo "Are you sure Java is installed?"; \
 	  exit 1; \
 	fi; \
 	if [ ! -f $(JAVA_JNI_MD_H_DIR)/jni_md.h ]; then \
-	  echo "Failed to locate the JNI header $(JAVA_JNI_MD_H_DIR)/jni_md.h"; \
+	  echo "Failed to locate the JNI header jni_md.h"; \
 	  echo "Are you sure Java is installed?"; \
 	  exit 1; \
 	fi)
